language: node_js

node_js:
  - lts/*
  # - node
  # - 12
  # - 11
  # - 10
  # - 9
  # - 8

os:
  - linux
  # - osx
  # - windows

sudo: false

notifications:
  email: false

cache:
  npm

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - npm run check:style
        - npm test

    - stage: release
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
