language: node_js

node_js:
  - lts/*
  - node
  - 12
  - 11
  - 10
  - 9
  - 8

os:
  - linux
  # - osx
  # - windows

sudo: false

notifications:
  email: false

cache:
  npm

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        # check code style
        - npm run lint

        # run tests with code coverage
        - npm test -- --coverage

        # report code coverage
        - npx codecov

    - stage: release
      script:
        - echo "skipping tests"

      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
        on:
          branch: master
